apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.lvm.name }}
provisioner: {{ .Values.driver }}
parameters:
  volumeType: "LVM"
  csi.storage.k8s.io/fstype: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.lvm_xfs.name }}
provisioner: {{ .Values.driver }}
parameters:
  volumeType: "LVM"
  csi.storage.k8s.io/fstype: xfs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.lvm_io.name }}
provisioner: {{ .Values.driver }}
parameters:
  csi.storage.k8s.io/fstype: ext4
  volumeType: "LVM"
  bps: "1048576"
  iops: "1024"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.device_hdd.name }}
provisioner: {{ .Values.driver }}
parameters:
  csi.storage.k8s.io/fstype: ext4
  volumeType: Device
  mediaType: hdd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.device_ssd.name }}
provisioner: {{ .Values.driver }}
parameters:
  csi.storage.k8s.io/fstype: ext4
  volumeType: Device
  mediaType: ssd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: {{ .Values.storageclass.lvm.name }}
driver: {{ .Values.driver }}
deletionPolicy: Delete
parameters:
  csi.aliyun.com/readonly: "true"
  csi.aliyun.com/snapshot-initial-size: 4Gi
  csi.aliyun.com/snapshot-expansion-size: 1Gi
  csi.aliyun.com/snapshot-expansion-threshold: 50%